package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/ryanfaerman/netctl/app/graph"
	"github.com/ryanfaerman/netctl/app/model"
)

// Channels is the resolver for the channels field.
func (r *netResolver) Channels(ctx context.Context, obj *model.Net) ([]model.Channel, error) {
	panic(fmt.Errorf("not implemented: Channels - channels"))
}

// Nets is the resolver for the nets field.
func (r *queryResolver) Nets(ctx context.Context) ([]*model.Net, error) {
	panic(fmt.Errorf("not implemented: Nets - nets"))
}

// Net returns graph.NetResolver implementation.
func (r *Resolver) Net() graph.NetResolver { return &netResolver{r} }

type netResolver struct{ *Resolver }
