package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"runtime"
	"time"

	"github.com/ryanfaerman/netctl/app/model"
	"github.com/ryanfaerman/version"
)

// System is the resolver for the system field.
func (r *queryResolver) System(ctx context.Context) (*model.System, error) {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)

	return &model.System{
		Version:   version.Version.String(),
		Uptime:    time.Now().Sub(startTime).Round(time.Second).String(),
		Processes: runtime.NumGoroutine(),
		Memory:    int(m.Sys),
	}, nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var (
	startTime = time.Now()
)
