// Code generated by "stringer -type=ContentType -linecomment"; DO NOT EDIT.

package web

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContentTypeText-0]
	_ = x[ContentTypeJSON-1]
	_ = x[ContentTypeXML-2]
	_ = x[ContentTypeYAML-3]
	_ = x[ContentTypeHTML-4]
}

const _ContentType_name = "plaintextjsonxmlyamlhtml"

var _ContentType_index = [...]uint8{0, 9, 13, 16, 20, 24}

func (i ContentType) String() string {
	if i < 0 || i >= ContentType(len(_ContentType_index)-1) {
		return "ContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentType_name[_ContentType_index[i]:_ContentType_index[i+1]]
}
